name: Tests

on:
  workflow_call:

jobs:

  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install skopeo
        run: |
          sudo snap install --devmode --channel edge skopeo

      - uses: actions/download-artifact@v3
        with:
          name: rock

      - name: Install tox
        run: |
          pip install tox

      - name: Tests
        run: |
          cd tests && tox -e integration
