name: Tests

on:
  workflow_call:

jobs:

  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install skopeo
        run: |
          sudo snap install --devmode --channel edge skopeo

      - name: Install yq
        run: |
          sudo snap install yq

      - uses: actions/download-artifact@v3
        with:
          name: rock

      - name: Import
        run: |
          image_name="$(yq '.name' rockcraft.yaml)"
          version="$(yq '.version' rockcraft.yaml)"
          rock_file=$(ls *.rock | tail -n 1)
          sudo skopeo \
            --insecure-policy \
            copy \
            oci-archive:"${rock_file}" \
            docker-daemon:"ghcr.io/canonical/${image_name}:${version}"

      - name: Install tox
        run: |
          pip install tox

      - name: Tests
        run: |
          image_name="$(yq '.name' rockcraft.yaml)"
          version="$(yq '.version' rockcraft.yaml)"
          export POSTGRES_USER=username
          export POSTGRES_PASSWORD=password
          export POSTGRES_DB=magma
          export DATABASE_SOURCE="dbname=magma user=username password=password host=172.17.0.2 sslmode=disable"
          docker run -d -p 5432:5432 --env POSTGRES_PASSWORD --env POSTGRES_USER --env POSTGRES_DB --network bridge postgres
          docker run -d -p 8080:10112 --network bridge ghcr.io/canonical/${image_name}:${version}
          cd tests && tox -e integration
